manifest:
  group-filter:
    - +babblesim
  projects:
    - name: nrf_hw_models
      url: https://github.com/tannewt/ext_nRF_hw_models
      revision: c2927847bdf2ee0af9c5459f4155c67f39f6837a
      path: modules/bsim_hw_models/nrf_hw_models
    - name: zephyr
      url: https://github.com/mikeysklar/zephyr
      revision: 33ff09e8976b9cce91957f9254178f639703364f
      clone-depth: 100
      import: true
